name: Security Checks

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  sast_sca:
    name: SAST & SCA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          if [ -f yarn.lock ]; then yarn --frozen-lockfile; elif [ -f package-lock.json ]; then npm ci; else npm i; fi
      - name: ESLint (SAST-like)
        run: |
          npm run lint || true
      - name: npm audit (SCA)
        run: |
          npm audit --audit-level=high || true

  container_scan:
    name: Container Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build -t app:scan .
      - name: Trivy filesystem and image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'image'
          image-ref: 'app:scan'
          format: 'sarif'
          output: 'trivy-image.sarif'
          exit-code: '0'
          vuln-type: 'os,library'
      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image.sarif'

  dast:
    name: DAST (ZAP baseline)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start app
        run: |
          npm i
          npm run build
          npm start &
          sleep 8
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          artifact_name: 'zapscan'
      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: '*.html'
